name = "websitegenerator"
description = "Generate static websites, easy and fast."
version = "0.0.0"

authors = ["Bent Bracke"]
maintainers = ["Bent Bracke <bent@bracke.dk>"]
maintainers-logins = ["bracke"]

executables = ["websitegenerator"]
[[depends-on]]  # Added by alr
aws = "^21.0.0"  # Added by alr
[[depends-on]]  # Added by alr
gnatcoll = "^21.0.0"  # Added by alr
[[depends-on]]  # Added by alr
clic = "~0.2.0"  # Added by alr
[[depends-on]]  # Added by alr
aaa = "~0.2.4"  # Added by alr
