name = "websitegenerator"
description = "Shiny new project"
version = "0.0.0"

authors = ["Bent Bracke"]
maintainers = ["Bent Bracke <bent@bracke.dk>"]
maintainers-logins = ["bracke"]

executables = ["websitegenerator"]
[[depends-on]]  # Added by alr
aws = "^21.0.0"  # Added by alr
[[depends-on]]  # Added by alr
gnatcoll = "^21.0.0"  # Added by alr
